---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: retraced-elasticsearch
spec:
  type: NodePort
  ports:
    - port: 9200
      nodePort: 30920
      targetPort: estransport
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |-
    http.host: 0.0.0.0

    http.port: 9200
    http.cors.allow-origin: "/.*/"
    http.cors.enabled: true
    http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
    http.cors.allow-credentials: true

    discovery.type: single-node

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: retraced-elasticsearch
spec:
  serviceName: elasticearch
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.8.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: estransport
              containerPort: 9200
          volumeMounts:
            - name: esdatadir
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml

          # command: ["sleep", "500d"]
      volumes:
        - name: esdatadir
          persistentVolumeClaim:
            claimName: esdatadir

        - name: elasticsearch
          configMap:
            name: elasticsearch
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml

  volumeClaimTemplates:
    - metadata:
        name: esdatadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
