include:
  - docker-compose-base.yaml

services:
  elasticsearch:
    image: elasticsearch:7.17.22
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - retraced
    restart: "always"

networks:
  retraced:
