apiVersion: skaffold/v4beta1
kind: Config
build:
  local:
    push: false
  platforms: ["linux/amd64", "linux/arm64"]
  artifacts:
    - image: retracedhq/retraced-local
      context: ./
      docker:
        dockerfile: ./deploy/Dockerfile-slim
manifests:
  kustomize:
    paths:
      - ./kustomize/overlays/dev
