apiVersion: skaffold/v4beta1
kind: Config
build:
  local:
    push: false

  artifacts:
    - image: retracedhq/retraced
      context: ./
      docker:
        dockerfile: ./deploy/Dockerfile-slim

manifests:
  kustomize:
    paths:
      - ./kustomize/overlays/skaffold
