#!/usr/bin/env node

const gri = require('gaze-run-interrupt'); 

gri([
    'src/handlers/**/*.ts',
    'src/test/**/*.ts',
    'src/security/**/*.ts',
    'src/persistence/**/*.ts',
    'src/*.ts',
], [{
    command: 'docker',
    args: ['exec', '-it', 'retraced.api', 'yarn', 'mintest']
}]);
