apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-admin-portal
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: admin-portal
          image: boxyhq/jackson:tagwillbereplaced
          imagePullPolicy: IfNotPresent
