apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-api
spec:
  template:
    spec:
      initContainers:
        - name: bootstrap
          image: retracedhq/retraced:tagwillbereplaced
      containers:
        - name: api
          image: retracedhq/retraced:tagwillbereplaced
          imagePullPolicy: IfNotPresent
