apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-processor
spec:
  template:
    spec:
      containers:
        - name: processor
          image: retracedhq/retraced:1.5.1
          imagePullPolicy: IfNotPresent
