apiVersion: apps/v1
kind: Deployment
metadata:
  name: retraced-cron
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cron
          command:
            - /bin/sh
            - -c
            - /usr/local/bin/retraced-auditlog-cron /crontab 2>&1 | grep ERRO
