---
bases:
  - ../../base

patchesStrategicMerge:
  - ./api-deployment.yaml
  - ./api-service.yaml
  - ./cron-deployment.yaml
  - ./migratepg-job.yaml
  - ./migratees-job.yaml
  - ./processor-deployment.yaml
  - ./admin-portal-deployment.yaml
  - ./admin-portal-service.yaml
