apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  selector:
    matchLabels:
      tier: api
  replicas: 2
  template:
    metadata:
      labels:
        app: auditlog
        tier: api
    spec:
      imagePullSecrets:
        - name: auditlog-imagepull-secret
      containers:
        - name: api
          readinessProbe:
            httpGet:
              port: 3000
              path: /healthz
          image: registry.replicated.com/shipretraced/retraced:1.3.1
          imagePullPolicy: IfNotPresent
          command:
            - /src/api
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: auditlog
          env:
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  key: API_TOKEN
                  name: auditlog
