apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbutil
  labels:
    app: retraced
    tier: dbutil
spec:
  selector:
    matchLabels:
      app: retraced
      tier: dbutil
  replicas: 1
  template:
    metadata:
      labels:
        app: retraced
        tier: dbutil
    spec:
      imagePullSecrets:
      - name: auditlog-imagepull-secret
      containers:
      - name: dbutil
        image: registry.replicated.com/shipretraced/retraced:1.3.1
        command:
        - /bin/sleep
        - infinity
        envFrom:
          - secretRef:
              name: auditlog
