apiVersion: v1
kind: Pod
metadata:
  name: migrate-es-1-3-1
spec:
  imagePullSecrets:
  - name: auditlog-imagepull-secret
  restartPolicy: Never
  containers:
  - name: db
    image: registry.replicated.com/shipretraced/retraced:1.3.1
    command:
    - /src/retraceddb
    - up
    - es
    envFrom:
    - secretRef:
        name: auditlog
    env:
    - name: BUGSNAG_TOKEN
      valueFrom:
        secretKeyRef:
          name: auditlog
          key: DB_TOKEN

