apiVersion: v1
kind: Service
metadata:
  name: retraced-admin-portal
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: auditlog
    tier: admin-portal
spec:
  type: LoadBalancer
  selector:
    app: auditlog
    tier: admin-portal
