apiVersion: v1
kind: Service
metadata:
  name: retraced-api
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: auditlog
    tier: api
spec:
  type: LoadBalancer
  selector:
    app: auditlog
    tier: api
