apiVersion: v1
kind: Service
metadata:
  name: retraced-api-internal
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: auditlog-internal
    tier: api
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: auditlog
    tier: api
