apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: retraced
    tier: api
spec:
  type: NodePort
  ports:
  - name: svcmain
    port: 80
    targetPort: 3000
  selector:
    app: retraced
    tier: api
