FROM node:8.7-alpine


RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
        patch

ADD . /src
WORKDIR /src

RUN yarn
RUN make build

RUN cp ./bin/retracedctl /usr/local/bin/retracedctl


FROM node:8.7-alpine
EXPOSE 3000
RUN apk update && apk add hiredis && rm -rf /var/cache/apk/*

COPY --from=0 /src /src
WORKDIR /src

CMD ["node", "--no-deprecation", "./build/index.js"]
