FROM postgres:10.23-alpine

RUN apk add --update --no-cache \
    ca-certificates \
  && apk add --upgrade --no-cache \
    apk-tools \
    krb5-libs \
    libcom_err \
    libgcrypt \
    ncurses-libs \
    ncurses-terminfo-base \
    openssl \
    busybox \
    ssl_client \
  && apk upgrade --no-cache

VOLUME /var/run/postgresql
