FROM postgres:10.23-alpine

RUN apk add --update --no-cache \
    ca-certificates \
  && apk add --upgrade --no-cache \
    \
    \
    apk-tools \
    openssl \
    libgcrypt

VOLUME /var/run/postgresql
