ARG NODEJS_IMAGE=node:18.16-alpine3.17
ARG ALPINE_IMAGE=alpine:3.17

# # #
# Cron build
#
FROM --platform=${BUILDPLATFORM:-linux/amd64} $ALPINE_IMAGE as cron

RUN apk add --update --no-cache ca-certificates curl \
  && rm -rf /tmp/* /var/cache/apk/*

ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.2.25/supercronic-linux-amd64
ENV SUPERCRONIC=supercronic-linux-amd64
ENV SUPERCRONIC_SHA1SUM=642f4f5a2b67f3400b5ea71ff24f18c0a7d77d49
RUN curl -fsSLO "$SUPERCRONIC_URL" \
  && echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
  && chmod +x "$SUPERCRONIC" \
  && mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
  && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/retraced-auditlog-cron
COPY deploy/crontab /crontab

# # #
# GeoIpUpdate build
#
FROM --platform=${BUILDPLATFORM:-linux/amd64} $ALPINE_IMAGE as geoipupdate

RUN apk add --update --no-cache ca-certificates curl \
  && rm -rf /tmp/* /var/cache/apk/*

ENV GEOIPUPDATE_URL=https://github.com/maxmind/geoipupdate/releases/download/v5.1.1/geoipupdate_5.1.1_linux_amd64.deb
ENV GEOIPUPDATE_SHA1SUM=a566c26128858d9b8967b7df8b94bae1042e49fe5b086b7cafe96443ebfa92ea
ENV GEOIPUPDATE=geoipupdate_5.1.1_linux_amd64.deb
RUN curl -fsSLO "$GEOIPUPDATE_URL" \
  && echo "${GEOIPUPDATE_SHA1SUM}  ${GEOIPUPDATE}" | sha256sum -c - \
  && apk add --no-cache --virtual .build-deps \
    dpkg \
  && dpkg --add-architecture amd64 \
  && dpkg -i "$GEOIPUPDATE" \
  && apk del .build-deps \
  && rm "$GEOIPUPDATE"

# # #
# Node build
#
FROM --platform=${BUILDPLATFORM:-linux/amd64} $NODEJS_IMAGE as node

#python
RUN apk add --no-cache --virtual .gyp \
  python3 \
  make \
  g++

WORKDIR /src
ADD package.json /src
ADD package-lock.json /src
RUN npm install

ADD . /src

RUN npm run build

FROM --platform=${BUILDPLATFORM:-linux/amd64} node as curl-builder

WORKDIR /app

ADD .env /app
ADD package.json /app
ADD package-lock.json /app

RUN npm install --omit=dev


# # #
# Main build
#
FROM $NODEJS_IMAGE

EXPOSE 3000

WORKDIR /app

# curl must be included for cron
RUN apk add --update --no-cache ca-certificates curl p11-kit \
  && rm -rf /tmp/* /var/cache/apk/*

ADD .env /app
ADD package.json /app

COPY --from=node /src/migrations /app/build/migrations
COPY --from=curl-builder /app/node_modules /app/node_modules
COPY --from=node /src/build /app/build
COPY --from=cron /usr/local/bin/supercronic-linux-amd64 /usr/local/bin/supercronic-linux-amd64
COPY --from=cron /usr/local/bin/retraced-auditlog-cron /usr/local/bin/retraced-auditlog-cron
COPY --from=cron /crontab /crontab
COPY --from=geoipupdate /usr/bin/geoipupdate /usr/bin/geoipupdate
COPY deploy/GeoIP.conf /etc/GeoIP.conf

CMD ["node", "build/src/index.js"]
