FROM node:8.7

ADD . /src
WORKDIR /src

RUN make deps build pkg


FROM debian:stretch-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libc6 \
    libc-bin \
    multiarch-support \
    systemd \
    libudev1 \
    libncurses5 \
    ncurses-base \
    ncurses-bin \
    libblkid1 \
    libfdisk1 \
    libmount1 \
    libsmartcols1 \
    libuuid1 \
    mount \
    util-linux \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

copy --from=0 /src/api /src/api
copy --from=0 /src/retracedctl /src/bin/retracedctl
COPY --from=0 /src/node_modules/snappy/build/Release/binding.node /src/node_modules/snappy/build/Release/binding.node
COPY --from=0 /src/node_modules/sse4_crc32/build/Release/sse4_crc32.node /src/node_modules/sse4_crc32/build/Release/sse4_crc32.node
WORKDIR /src

CMD ["/src/api"]
