
# # #
# Node build
#
FROM node:8.7 as node

ADD . /src
WORKDIR /src

RUN make deps
RUN npm run snyk-protect
RUN make build pkg

# # #
# Cron build
#
FROM debian:stretch-slim as cron

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    libicu57 \
    libssl1.1 \
    openssl \
    perl-base \
    gpgv \
    libgcrypt20 \
  && rm -rf /var/lib/apt/lists/*


ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.1.3/supercronic-linux-amd64
ENV SUPERCRONIC=supercronic-linux-amd64
ENV SUPERCRONIC_SHA1SUM=96960ba3207756bb01e6892c978264e5362e117e
RUN curl -fsSLO "$SUPERCRONIC_URL" \
    && echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
    && chmod +x "$SUPERCRONIC" \
    && mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
    && ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/replicated-auditlog-cron
COPY ./crontab /crontab



# # #
# Main build
#
FROM debian:stretch-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libicu57 \
    libssl1.1 \
    openssl \
    perl-base \
    gpgv \
    libgcrypt20 \
  && rm -rf /var/lib/apt/lists/*

EXPOSE 3000

COPY --from=node /src/api /src/api
COPY --from=node /src/retracedctl /src/bin/retracedctl
COPY --from=node /src/processor /src/processor
COPY --from=node /src/node_modules/snappy/build/Release/binding.node /src/node_modules/snappy/build/Release/binding.node
COPY --from=node /src/node_modules/sse4_crc32/build/Release/sse4_crc32.node /src/node_modules/sse4_crc32/build/Release/sse4_crc32.node
COPY --from=node /src/node_modules/bcrypt/lib/binding/bcrypt_lib.node /src/node_modules/bcrypt/lib/binding/bcrypt_lib.node
COPY --from=cron /usr/local/bin/supercronic-linux-amd64 /usr/local/bin/supercronic-linux-amd64
COPY --from=cron /usr/local/bin/replicated-auditlog-cron /usr/local/bin/replicated-auditlog-cron
COPY --from=cron /crontab /crontab

RUN cp /src/api /src/replicated-auditlog-api
RUN cp /src/bin/retracedctl /src/replicated-auditlog-retracedctl
RUN cp /src/processor /src/replicated-auditlog-processor

WORKDIR /src

CMD ["/src/replicated-auditlog-api"]
