apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - $patch: delete
          name: auditlog-imagepull-secret
        - name: replicatedregistrykey
