apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-es-1-3-1
spec:
  template:
    spec:
      imagePullSecrets:
      - $patch: delete
        name: auditlog-imagepull-secret
      - name: replicatedregistrykey
