apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: retraced-elasticsearch
spec:
  serviceName: elasticearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.14.3
          imagePullPolicy: IfNotPresent
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enabled
              value: false
          ports:
            - name: estransport
              containerPort: 9200
          volumeMounts:
            - name: esdatadir
              mountPath: /usr/share/elasticsearch/data

      volumes:
        - name: esdatadir
          persistentVolumeClaim:
            claimName: esdatadir

  volumeClaimTemplates:
    - metadata:
        name: esdatadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
