apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: auditlog
    tier: api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: auditlog
    tier: api
