apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-es-1-3-12
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  template:
    spec:
      imagePullSecrets:
      - name: auditlog-imagepull-secret
      restartPolicy: Never
      containers:
      - name: db
        image: registry.replicated.com/shipretraced/retraced:1.3.12
        command:
        - /src/retraceddb
        - es
        - up
        envFrom:
        - secretRef:
            name: auditlog
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              name: auditlog
              key: DB_TOKEN

