api:
  api:
    env:
      exportPageSizeInternal: "2"
    image:
      repository: retracedhq/retraced
      tag: 1.12.1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: 100m
  bootstrap:
    args:
    - -c
    - ./build/src/retracedctl bootstrap --projectName   "$BOOTSTRAP_PROJECT_NAME"
      --projectId     "$BOOTSTRAP_PROJECT_ID" --environmentId "$BOOTSTRAP_ENVIRONMENT_ID"
      --apiKey        "$BOOTSTRAP_API_TOKEN"
    image:
      repository: retracedhq/retraced
      tag: 1.12.1
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  replicas: 1
  type: LoadBalancer
apiInternal:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP
auditlog:
  adminRootToken: "dev"
  apiBaseUrlPath: "/auditlog"
  apiToken: ""
  dbToken: ""
  elasticsearchNodes: "http://user:password@retraced-elasticsearch:9200"
  geoipupdateAccountId: ""
  geoipupdateDbDir: "/etc/mmdb"
  geoipupdateEditionIds: "GeoLite2-City"
  geoipupdateFrequency: "168"
  geoipupdateLicenseKey: ""
  geoipupdateUseMmdb: ""
  geoipupdateVerbose: "1"
  hmacSecretAdmin: "xxxxxxx"
  hmacSecretViewer: "xxxxxxxxx"
  logLevel: "info"
  mandrillKey: ""
  nsqdHost: "retraced-nsqd"
  nsqdHttpPort: "4151"
  nsqdTcpPort: "4150"
  postgresDatabase: "retraced"
  postgresHost: "retraced-postgres"
  postgresPassword: "password"
  postgresPoolSize: "10"
  postgresPort: "5432"
  postgresUser: "retraced"
  processorToken: ""
  retracedApiBase: "http://localhost:3000/auditlog"
  retracedDisableGeosync: ""
  stage: ""
  statsdHost: ""
  statsdPort: ""
bootstrap:
  bootstrapApiToken: "dev"
  bootstrapEnvironmentId: "dev"
  bootstrapProjectId: "dev"
  bootstrapProjectName: "dev"
cron:
  cron:
    image:
      repository: retracedhq/retraced
      tag: v1.12.1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 10m
  replicas: 1
dbutil:
  dbutil:
    image:
      repository: retracedhq/retraced
      tag: 1.12.1
  replicas: 1
kubernetesClusterDomain: cluster.local
migrateEs:
  db:
    env:
      schemaPath: /app/build/migrations/es
    image:
      repository: retracedhq/retraced
      tag: 1.12.1
migratePg:
  db:
    env:
      schemaPath: /app/build/migrations/pg/*
    image:
      repository: retracedhq/retraced
      tag: 1.12.1
nsqd:
  nsqd:
    args:
    - -c
    - nsqd -statsd-address ${STATSD_HOST}:${STATSD_PORT} -statsd-prefix "nsqd."
    image:
      repository: nsqio/nsq
      tag: v1.2.1
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: 100m
  ports:
  - name: tcp
    port: 4150
    targetPort: 4150
  - name: http
    port: 4151
    targetPort: 4151
  replicas: 1
  type: ClusterIP
processor:
  processor:
    env:
      pgSearch: ""
      tmpdir: /tmp
    image:
      repository: retracedhq/retraced
      tag: 1.12.1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: 100m
  replicas: 1
pvc:
  mmdbdir:
    storageRequest: 1Gi
