---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retraced-mmdbdir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-geoipupdate
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: geoipupdate
          image: maxmindinc/geoipupdate:v5.1
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              if [ -z "$GEOIPUPDATE_USE_MMDB" ]; then
                echo "Skipping the job..."
              else
                echo "Running the job..."
                source /usr/bin/entry.sh
              fi
          envFrom:
            - secretRef:
                name: auditlog
          env:
            - name: GEOIPUPDATE_EDITION_IDS
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: GEOIPUPDATE_EDITION_IDS
            - name: GEOIPUPDATE_FREQUENCY
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: GEOIPUPDATE_FREQUENCY
            - name: GEOIPUPDATE_USE_MMDB
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: GEOIPUPDATE_USE_MMDB
            - name: GEOIPUPDATE_VERBOSE
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: GEOIPUPDATE_VERBOSE
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: GEOIPUPDATE_ACCOUNT_ID
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: GEOIPUPDATE_LICENSE_KEY
            - name: GEOIPUPDATE_DB_DIR
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: GEOIPUPDATE_DB_DIR
          volumeMounts:
            - name: retraced-mmdbdir
              mountPath: /etc/mmdb

      volumes:
        - name: retraced-mmdbdir
          persistentVolumeClaim:
            claimName: retraced-mmdbdir
