apiVersion: v1
kind: Service
metadata:
  name: jackson-admin-ui
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: auditlog
    tier: admin-ui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5225
      targetPort: 5225
  selector:
    app: auditlog
    tier: admin-ui
