apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-pg-1-3-20
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db
        image: registry.replicated.com/shipretraced/retraced:1.3.20
        imagePullPolicy: IfNotPresent
        command:
        - /src/retraceddb
        - pg
        - up
        envFrom:
        - secretRef:
            name: auditlog
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              name: auditlog
              key: DB_TOKEN
        - name: SCHEMA_PATH
          value: "/src/migrations/pg10"
      imagePullSecrets:
      - name: auditlog-imagepull-secret
