apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-es-1-4-6
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db
        image: retraced-api
        command:
        - /src/retraceddb
        - es
        - up
        envFrom:
        - secretRef:
            name: retraced-auditlog
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              name: retraced-auditlog
              key: DB_TOKEN
