apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-pg-1-4-6
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db
        image: retraced-api
        imagePullPolicy: IfNotPresent
        command:
        - /src/retraceddb
        - pg
        - up
        envFrom:
        - secretRef:
            name: retraced-auditlog
        env:
        - name: BUGSNAG_TOKEN
          valueFrom:
            secretKeyRef:
              name: retraced-auditlog
              key: DB_TOKEN
        - name: SCHEMA_PATH
          value: "/src/migrations/pg10"