apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-pg-1-4-6
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db
          image: retracedhq/retraced:1.4.6
          imagePullPolicy: IfNotPresent
          command:
            - /src/retraceddb
            - pg
            - up
          envFrom:
            - secretRef:
                name: auditlog
          env:
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: DB_TOKEN
            - name: SCHEMA_PATH
              value: "/src/migrations/pg"
