apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-es
  namespace: '{{repl ConfigOption "namespace"}}'
spec:
  template:
    spec:
      restartPolicy: "OnFailure"
      containers:
        - name: db
          image: retracedhq/retraced-local
          command:
            - node
            - --inspect=0.0.0.0
            - build/src/_db/runner-lite.js
            - es
          envFrom:
            - secretRef:
                name: auditlog
          env:
            - name: BUGSNAG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: auditlog
                  key: DB_TOKEN
            - name: SCHEMA_PATH
              value: "/app/build/migrations/es"
