apiVersion: v1
kind: Secret
metadata:
  name: auditlog-imagepull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{repl print "{\"auths\": {\"registry.replicated.com\":{\"username\":\"" (Installation "license_id") "\",\"password\":\"" (Installation "license_id") "\" } } } " | Base64Encode }}
