apiVersion: v1
kind: Pod
metadata:
  name: retraced-integrationtest
spec:
  restartPolicy: OnFailure
  containers:
    - name: tests
      image: registry.replicated.com/library/retraced
      command:
        - npx
        - mocha
        - -r
        - ts-node/register
        - integration/test/**/*.ts
      env:
        - name: PUBLISHER_API_ENDPOINT
          value: http://retraced-api:3000/auditlog
        - name: PROJECT_ID
          value: dev
        - name: ENVIRONMENT_ID
          value: dev
        - name: PUBLISHER_API_KEY
          value: dev
        - name: ES_INDEX_WAIT_MS
          value: "2000"
      envFrom:
        - secretRef:
            name: auditlog
