apiVersion: v1
kind: Pod
metadata:
  name: integrationtest
spec:
  restartPolicy: OnFailure
  containers:
    - name: tests
      image: registry.replicated.com/shipretraced/retraced:1.3.39
      command:
        - npx
        - mocha
        - -r
        - ts-node/register
        - integration/test/**/*.ts
      env:
        - name: PUBLISHER_API_ENDPOINT
          value: http://api:3000/auditlog
        - name: PROJECT_ID
          value: dev
        - name: ENVIRONMENT_ID
          value: dev
        - name: PUBLISHER_API_KEY
          value: dev
      envFrom:
        - secretRef:
            name: auditlog
