apiVersion: v1
kind: Service
metadata:
  name: api-lb
  namespace: '{{repl ConfigOption "namespace"}}'
  labels:
    app: auditlog
    tier: api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3001
      targetPort: http
  selector:
    app: auditlog
    tier: api

