apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-es-1-3-39
spec:
  template:
    spec:
      imagePullSecrets:
      - $patch: delete
        name: auditlog-imagepull-secret
      containers:
      - name: db
        command:
        - node
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/_db/runner-lite.ts
        - es
