apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-es-1-4-6
spec:
  template:
    spec:
      containers:
        - name: db
          command:
            - node
            - --inspect=0.0.0.0
            - build/src/_db/runner-lite.js
            - es
