apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-pg-1-4-6
spec:
  template:
    spec:
      containers:
        - name: db
          command:
            - node
            - --inspect=0.0.0.0
            - -r
            - ts-node/register
            - src/_db/runner-lite.ts
            - pg
