apiVersion: batch/v1
kind: Job
metadata:
  name: retraced-migrate-pg-1-4-6
spec:
  template:
    spec:
      imagePullSecrets:
      - $patch: delete
        name: auditlog-imagepull-secret
      containers:
      - name: db
        image: retraced-api
        command:
        - node
        - --no-deprecation
        - --inspect=0.0.0.0
        - -r
        - ts-node/register
        - src/_db/runner-lite.ts
        - pg