# secrets.yaml for auditlog. This file is generated as a template to aid in
# deploying the necessary secrets.
#
# COMMITTING THIS FILE IS STRONGLY DISCOURAGED. Instead, it is recommended that you
# fill it out manually for now and deploy the secrets out of band, or use
# a solution like [sealed secrets](https://github.com/bitnami-labs/sealed-secrets)
# to manage this information.
---
apiVersion: v1
kind: Secret
metadata:
  name: auditlog
  labels:
    app: auditlog
stringData:
  # nsq settings, these shouldn't change
  NSQD_HOST: retraced-nsqd
  NSQD_TCP_PORT: "4150"
  NSQD_HTTP_PORT: "4151"
  LOG_LEVEL: "info"

  # postgres settings
  POSTGRES_POOL_SIZE: "10"
  POSTGRES_USER: "retraced"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "retraced-postgres"
  POSTGRES_DATABASE: "retraced"
  POSTGRES_PORT: "5432"
  # a comma-separated list of one or more elasticsearch connection strings
  ELASTICSEARCH_NODES: http://user:password@retraced-elasticsearch:9200
  # secure random strings for use in session signing
  HMAC_SECRET_ADMIN: "xxxxxxx"
  HMAC_SECRET_VIEWER: "xxxxxxxxx"

  # # # # #
  # Optional
  # # # # #

  # the URL that browser clients will use to communicate with retraced. Can be omitted if not using embedded viewer
  RETRACED_API_BASE: "http://localhost:3000/auditlog"
  API_BASE_URL_PATH: "/auditlog"
  ADMIN_ROOT_TOKEN: "dev"

  # statsd settings
  STATSD_HOST: ""
  STATSD_PORT: ""

  # optional, tokens to report errors to bugsnag
  PROCESSOR_TOKEN: ""
  API_TOKEN: ""
  DB_TOKEN: ""
  # usually one of `staging` or `production`
  STAGE: ""
  # optional, a mandrill key for email alerts
  MANDRILL_KEY: ""

  # MaxMind GeoIP settings
  RETRACED_DISABLE_GEOSYNC: ""
  GEOIPUPDATE_LICENSE_KEY: ""
  GEOIPUPDATE_ACCOUNT_ID: ""
  GEOIPUPDATE_USE_MMDB: ""
  GEOIPUPDATE_DB_DIR: "/etc/mmdb"
  GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
  GEOIPUPDATE_FREQUENCY: "168"
  GEOIPUPDATE_VERBOSE: "1"

  # Vector Sidecar
  VECTOR_SIDECAR_PORT: "3002"
  VECTOR_API_PORT: "8686"
